### ISSUE TITLE
this variable is unused?

### ISSUE THREAD

**Issue by Little-Ki** [Broihon/GH-Injector-Library#13]
https://github.com/Broihon/GH-Injector-Library/blob/d8f3220c9476b4e88fa1a8ba7bc763e3ecf2cc0d/GH%20Injector%20Library/Manual%20Mapping.cpp#L957

**Comment by Little-Ki** [comment]
Process of processing delayed input tables ... it load target module then set member ModuleHandleRVA to target module base, the following code seem does nothing?

**Comment by Little-Ki** [comment]
maybe insert code follow line 986 ? :
*pIAT = pFunc;

**Comment by Broihon** [comment]
The delay load IAT works differently than the "normal" IAT. It's a list of callbacks generated by the compiler that when called check if the required module is loaded. If not it loads the module and resolves the addresses. Then it forwards the call to the desired function.

LdrGetProcedureAddress however needs a buffer to work which is why I'm just passing pFunc to it. I'm using LdrGetProcedureAddress only to verify that the desired function exists.

**Comment by Broihon** [comment]
I did some more research it seems like the offset in the IAT itself gets redirected to the delayed import. So I should be able to patch it.

**Comment by Broihon** [comment]
`ntRet = f->LdrGetProcedureAddress(ReCa<void *>(hDll), import, IMAGE_ORDINAL(pNameTable->u1.Ordinal), ReCa<void **>(pIAT));`
Works fine, not sure how I missed this before. Thanks!
